repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-toml
    -   id: double-quote-string-fixer
    -   id: fix-encoding-pragma
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
    - id: isort
